# Rendered at deploy-time via envsubst with GH Actions secrets in scope.
KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
DATABASE_URL=$STAGING_DATABASE_URL
POSTGRES_PASSWORD=$STAGING_POSTGRES_PASSWORD
REDIS_URL=$STAGING_REDIS_URL
