service: vmkit-test-fullstack-staging
image: badri/vmkit-test-fullstack
servers:
  web:
    hosts:
    - $DEST_VM_HOST
proxy:
  ssl: false
  host: vmkit-test-fullstack-staging.vmkit.app
  app_port: 8000
  healthcheck:
    path: /health
    interval: 3
    timeout: 30
registry:
  server: ghcr.io
  username: vmkit-deploy[bot]
  password:
  - KAMAL_REGISTRY_PASSWORD
ssh:
  user: kamal
builder:
  arch: arm64
env:
  clear:
    PYTHONUNBUFFERED: '1'
  secret:
  - REDIS_URL
accessories:
  redis:
    image: redis:7-alpine
    host: $DEST_VM_HOST
    port: 6379
